apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - name: kube-apiserver
    image: k8s.gcr.io/kube-apiserver:v1.27.0
    command:
    - kube-apiserver
    - --advertise-address=192.168.10.10
    - --etcd-servers=https://192.168.10.11:2379,https://192.168.10.12:2379
    - --authorization-mode=Node,RBAC
