apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: kube-system
spec:
  containers:
  - name: etcd
    image: k8s.gcr.io/etcd:3.5.0
    command:
    - etcd
    - --name=etcd1
    - --data-dir=/var/lib/etcd
    - --initial-cluster-state=new
