apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark
    role: worker
spec:
  replicas: 2  # You can adjust the number of worker replicas
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      containers:
        - name: spark-worker
          image: bde2020/spark-worker:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPARK_MODE
              value: "worker"
            - name: SPARK_MASTER
              value: "spark://spark-master:7077"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
spec:
  type: ClusterIP
  ports:
    - port: 8081
      name: spark-worker-ui
  selector:
    app: spark
    role: worker
