apiVersion: v1
kind: Pod
metadata:
  name: db-app-env
spec:
  containers:
  - name: app
    image: alpine
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: DB_PASSWORD
