apiVersion: v1
kind: Pod
metadata:
  name: db-app-volume
spec:
  containers:
  - name: app
    image: alpine
    volumeMounts:
    - name: secret-vol
      mountPath: /etc/secret
      readOnly: true
  volumes:
  - name: secret-vol
    secret:
      secretName: db-credentials
