name: CI Pipeline with Vulnerability Scanning

on:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Trivy Image Scan
      run: |
        docker build -t myapp:${{ github.sha }} .
        trivy image --exit-code 1 --severity HIGH,CRITICAL myapp:${{ github.sha }}

    - name: Polaris YAML Scan
      uses: FairwindsOps/polaris-action@master
