apiVersion: batch/v1
kind: Job
metadata:
  name: batch-processing
spec:
  template:
    spec:
      containers:
      - name: job
        image: busybox
        command: ["echo", "Processing completed"]
      restartPolicy: Never
