name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Scan Kubernetes YAML with Polaris
      uses: FairwindsOps/polaris-action@master

    - name: Scan Container Image with Trivy
      run: |
        docker build -t myapp:${{ github.sha }} .
        trivy image myapp:${{ github.sha }}

    - name: Run kube-bench
      run: kube-bench --version 1.27
