apiVersion: v1
kind: Pod
metadata:
  name: gpu-ml-inference
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: accelerator
            operator: In
            values:
            - nvidia-gpu
  containers:
  - name: model
    image: myregistry.azurecr.io/ml-inference:latest
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
