apiVersion: batch/v1
kind: CronJob
metadata:
  name: etl-daily-cronjob
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etl-job
            image: your-registry/etl:latest
            volumeMounts:
            - name: etl-volume
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: etl-volume
            persistentVolumeClaim:
              claimName: etl-pvc
